### ISSUE TITLE
Errori vari

### ISSUE THREAD

**Issue by vince87** [gdelpuente/thdns#1]
Ciao, e complimenti per il progetto!
Premetto che lanciando lo script da windows con python27 va alla perfezione, però lanciandolo dal mio router con installato openwrt mi da questi errori:

```
root@OpenWrt:~#` python thdns.py -f
Traceback (most recent call last):
  File "thdns.py", line 190, in <module>
    getsid()
  File "thdns.py", line 95, in getsid
    conn.endheaders()
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
  File "/usr/lib/python2.7/httplib.py", line 844, in send
  File "/usr/lib/python2.7/httplib.py", line 1263, in connect
  File "/usr/lib/python2.7/ssl.py", line 369, in wrap_socket
  File "/usr/lib/python2.7/ssl.py", line 617, in __init__
  File "/usr/lib/python2.7/ssl.py", line 846, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c:726)
```

Ho provato anche a lanciarlo con python3.6 ma nulla, dice che ci sono degli errori di sintassi

Hai qualche idea?
Grazie
Vincenzo

**Comment by vince87** [comment]
Mi autorispondo:
ho aggunto:
`PYTHONHTTPSVERIFY=0`
