### ISSUE TITLE
Script non funzionante

### ISSUE THREAD

**Issue by manuzzo24** [gdelpuente/thdns#2]
Ciao Guido,
stavo provando ad eseguire questo script per il mio sito Top Host, tuttavia riscontro il seguente errore durante l'esecuzione.

Traceback (most recent call last):
  File "C:\Users\manuz\Desktop\thdns.py", line 216, in <module>
    getsid()
  File "C:\Users\manuz\Desktop\thdns.py", line 104, in getsid
    node=x_httpsstatus.getheader('set-cookie').split(',')[0]
AttributeError: 'NoneType' object has no attribute 'split'

Sapresti aiutarmi?
Mi chiedevo anche se fosse possibile per te aggiornare lo script a Python3.

Grazie

**Comment by simone7121** [comment]
Ho lo stesso problema
